In [1]:
import numpy as np

### Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.01516026, 0.28748162, 0.21316046],
        [0.23948356, 0.56813287, 0.76938522],
        [0.6305844 , 0.6802216 , 0.90974787]],

       [[0.32649057, 0.91431465, 0.45274008],
        [0.85425541, 0.60590321, 0.41942912],
        [0.1536342 , 0.85001863, 0.50185686]],

       [[0.42045046, 0.41502991, 0.43591905],
        [0.60665137, 0.75964279, 0.05433294],
        [0.8777618 , 0.29648863, 0.78448318]]])

### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
print("Original Matrix \n",arr)
arr1 = (arr - np.mean (arr)) / (np.std (arr))
print("\n\nNormalized Matrix \n",arr1)

Original Matrix 
 [[0.06163291 0.37676409 0.52107943 0.00223985 0.93334492]
 [0.12924178 0.54521868 0.40639062 0.71805465 0.6914037 ]
 [0.66525174 0.49999185 0.88177755 0.79866521 0.02059188]
 [0.07729977 0.22494497 0.99014255 0.77635438 0.69967473]
 [0.63702645 0.14114781 0.37399456 0.13806547 0.38564327]]


Normalized Matrix 
 [[-1.3509118  -0.30288277  0.17706552 -1.54843481  1.54813331]
 [-1.12606559  0.2573452  -0.20435406  0.8321443   0.74351147]
 [ 0.65653814  0.10693474  1.37663615  1.10023017 -1.48740163]
 [-1.29880869 -0.80778629  1.73702472  1.02603123  0.77101838]
 [ 0.56266952 -1.08646979 -0.31209335 -1.09672071 -0.27335336]]


### How to find common values between two arrays

In [6]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,5,6])

np.intersect1d(arr1, arr2)

array([2, 3, 5])

### How to get the dates of yesterday, today and tomorrow?

In [7]:
from datetime import date, timedelta
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Yesterday :",yesterday,"\nToday :", today,"\nTomorrow :", tomorrow)

Yesterday : 2020-07-26 
Today : 2020-07-27 
Tomorrow : 2020-07-28


### Consider two random array A and B, check if they are equal

In [8]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.48851396 0.69702148 0.74904686]
 [0.3208558  0.55190468 0.77603725]
 [0.15221586 0.98665185 0.19059139]]


Array2:
[[0.62679152 0.90978645 0.73783244]
 [0.28534426 0.5781111  0.61000183]
 [0.87032414 0.06567677 0.92805951]]


Equality: False


### Create random vector of size 10 and replace the maximum value by 0

In [9]:
arr = np.random.rand(10)
print("Array is :",arr)
arr[arr.argmax()] = 0
print("New Array :",arr)

Array is : [0.36496944 0.36738242 0.89455137 0.00507606 0.47582923 0.88528896
 0.23260024 0.06338827 0.27093303 0.56950563]
New Array : [0.36496944 0.36738242 0.         0.00507606 0.47582923 0.88528896
 0.23260024 0.06338827 0.27093303 0.56950563]


### How to print all the values of an array?

In [10]:
arr = np.ones((5, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Subtract the mean of each row of a matrix

In [11]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[-0.47156126,  0.11122459,  0.36033667],
       [-0.0383392 ,  0.1527984 , -0.1144592 ],
       [ 0.29552647, -0.14715728, -0.14836919]])

### Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
a = np.ones(10)
print("Initial Vector:\n",a)
b = np.random.randint(0, len(a),20)
print("Random Values:\n",b)
a += np.bincount(b, minlength=len(a))
print("Resultant Vector:\n",a)

Initial Vector:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Random Values:
 [7 6 6 2 1 0 4 0 7 5 0 2 9 8 9 7 3 8 6 7]
Resultant Vector:
 [4. 2. 3. 2. 2. 2. 4. 5. 3. 3.]


### How to get the diagonal of a dot product?

In [13]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))
print("Array1 :\n",arr1)
print("Array2 :\n",arr2)
np.diag(np.dot(arr1, arr2))

Array1 :
 [[6 0 0]
 [9 9 9]
 [7 8 5]]
Array2 :
 [[6 9 2]
 [3 2 3]
 [7 5 2]]


array([ 36, 144,  48])

### How to find the most frequent value in an array?

In [14]:
arr = np.random.randint(0,10,20)
print(arr)
np.bincount(arr).argmax()

[3 3 7 8 9 6 8 8 8 2 9 0 8 3 3 4 7 0 4 1]


8

### How to get the n largest values of an array

In [15]:
arr = np.random.randint(0,1000,50)
print(arr)
np.random.shuffle(arr)
n = int(input('Enter the value of n: '))
print(f"{n} Largest values in array: ", arr[np.argsort(arr)[-n:]])

[756  78 185 727 668 227 489 808 260 320 475 765 926 675 385 347 677 398
 573 951 322 233 582 540 471 764 455  18  75 755 341 767 464 994 931 919
 757 791 435 240 191 791 812 802 225 385 595 614 558 552]
Enter the value of n: 6
6 Largest values in array:  [812 919 926 931 951 994]


### How to create a record array from a regular array?

In [16]:
arr = np.array([("English", 81, 73),
                 ("Maths", 95, 99),
             ("Hisory", 90.5, 93)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T, names='col1, col2, col3', formats = 'S80, f8, i8')
print(record)
type(record)

[['English' '81' '73']
 ['Maths' '95' '99']
 ['Hisory' '90.5' '93']]

RECORD ARRAY
[(b'English', 81. , 73) (b'Maths', 95. , 99) (b'Hisory', 90.5, 93)]


numpy.recarray